#MySQL配置
mysql:
  url: jdbc:mysql://172.22.4.113:3306/hand_todo?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: hzero
  password: hzero

# MyBatis Mapper 扫描
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

# Spring配置
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${mysql.url}}
    username: ${SPRING_DATASOURCE_USERNAME:${mysql.username}}
    password: ${SPRING_DATASOURCE_PASSWORD:${mysql.password}}

# 日志配置
logging:
  level:
    org.hzero: ${LOG_LEVEL:debug}
    org.apache.ibatis: ${LOG_LEVEL:debug}
    io.choerodon: ${LOG_LEVEL:debug}
