# Spring配置
spring:
  profiles:
    include: ${SPRING_PROFILES_INCLUDE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL:${mysql.url}}
    username: ${SPRING_DATASOURCE_USERNAME:${mysql.username}}
    password: ${SPRING_DATASOURCE_PASSWORD:${mysql.password}}
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
      # 连接池允许的最大连接数
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
  redis:
    host: ${SPRING_REDIS_HOST:${redis.host}}
    port: ${SPRING_REDIS_PORT:${redis.port}}
    database: ${SPRING_REDIS_DATABASE:${redis.database}}
    password: ${SPRING_REDIS_PASSWORD:${redis.password}}
    jedis:
      pool:
        # 资源池中最大连接数
        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
        max-active: ${SPRING_REDIS_POOL_MAX_ACTIVE:50}
        # 资源池运行最大空闲的连接数
        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
        max-idle: ${SPRING_REDIS_POOL_MAX_IDLE:50}
        # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
        # 默认 -1 表示永不超时，设置5秒
        max-wait: ${SPRING_REDIS_POOL_MAX_WAIT:5000}
  web:
    resources:
      cache:
        # 资源缓存时间，单位秒
        period: 3600
      chain:
        # 启用缓存
        cache: true
        # 开启gzip压缩
        compressed: true

# MyBatis Mapper 扫描
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

# 日志配置
logging:
  level:
    org.hzero: ${LOG_LEVEL:debug}
    org.apache.ibatis: ${LOG_LEVEL:debug}
    io.choerodon: ${LOG_LEVEL:debug}
